id: P7C5DB05E
initial_creation_type: input
source_metadata:
  title: Dharma Protectors Series
  language: es
  description: 'The following texts are now available as part of our Dharma Protectors
    (dharmapāla; Tib. chos skyong) series:'
  volume:
    f45991a0c66a4a629489b61b9e51db82:
      title: Brief Dharmapālas Offering
      parent: General
    95b6f493ff6843ceb1d51479c46b2649:
      title: Brief Protectors Practice
      parent: General
    eb978545aa174764a1a426c2f8c79e5a:
      title: Expeditious Activity Torma Offering
      parent: General
    1c6caa5bc7904df08dfe1f0bc766dd38:
      title: Wayfaring Offering
      parent: General
    8dcce784956846efb6ec040d37aa7d80:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: General
    506cce729ce74095aa72e1f7c82518c6:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: General
    581c5253bc964737a0ef3cac6e667015:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Changshönma
    98bffdad000943e08b7664657ff044ac:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Durtrö Lhamo
    42e91cba5ea74a96965daf3c8e803db3:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Eight Classes
    f92f1f4f26b34d28926cf85be4ccd79c:
      title: Restorative Offering to the Eight Classes
      parent: Eight Classes
    fcae677e35304b7fa7b1637104e916a8:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Ekajaṭī
    a4caf9c2917b49d481b4de9451bcaab5:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Five Medicine Sisters
    12dace0c6b5f4792b6b0b758a3bf6d76:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Gesar
    6bccf40a0e5041aa9a6231ba83e27547:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    661c43563bf74739a76cd0f6cbdf202e:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    eb0740fd8868422595163a7fdd00ffdb:
      title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer
        to Mahākāla and Consort'
      parent: Mahākāla
    b31f2b8033524bd1bcfd38e570cf7470:
      title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to
        the Glorious Guru Mahākāla Pañjaranātha'
      parent: Mahākāla
    6cea287417dd456c908d871ac2c7dac7:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
    cb85e4c44f38475188a88a6425b58fe8:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Pacifying the Turmoil of the Mamos
    7510f22a90e04267a4d1bf3d3be2bf5a:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Pacifying the Turmoil of the Mamos
    6d0f30eb7650499b89acd58aedb114e5:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Pukkasī
    babd692efb5846c1be0f3df3e5d16dd1:
      title: Brief Offering Prayer to Za Rāhula
      parent: Rāhula
    f766a3613ae3424f87489abeaf1095d9:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Serkyem
    4e01f092d6564281b48027ce3a96f103:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Tsiu Marpo
    abab60147e8b4fc2a30afed47a8ea037:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Vajrasādhu
    f84ceb3a950a4c459735fdbdb443df19:
      title: Yarlha Shampo Sang Offering
      parent: Yarlha Shampo
created_at: '2022-03-01T03:27:20.281733'
last_modified_at: '2022-03-01T03:27:20.281736'
